# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI with Maven

on:
  push:
    branches: [ "main", "release/1.0.0" ]
  pull_request:
    branches: [ "main", "release/1.0.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Set up Firefox
      uses: browser-actions/setup-firefox@v1

    - name: Set up Edge
      uses: browser-actions/setup-edge@v1

    - name: Build with Maven
      run: mvn clean verify -Dspring.profiles.active="test" -Dcucumber.execution.parallel.enabled=true -Dcucumber.filter.tags="@SamplePages_01" -Djasypt.encryptor.password="Tester123" -Denvironment="chrome-headless"

    - name: Upload Serenity Report
      uses: actions/upload-artifact@v4
      with:
        name: serenity-report
        path: target/site/serenity/
